auth:
  # Needed for mTLS (This plugin doesn't use username/password authentication to keep your system safe)
  #   mTLS - What lets the server know you are authorized to make changes
  #          to plugins and to accept those changes.
  #
  # ---------------------------------------------------------------------------------------------
  # !!!DO NOT PUBLISH OR GIVE THE CLIENT.KEY TO ANYONE YOU DON'T TRUST WITH YOUR ENTIRE SYSTEM!!!
  #
  # MINECRAFT SERVERS RUN WITH COMPLETE CONTROL OVER YOUR SYSTEM, GIVING SOMEONE THE CLIENT.KEY
  # IS GIVING THEM COMPLETE ACCESS TO YOUR SYSTEM VIA. THE MINECRAFT SERVER!
  #
  # DISTRIBUTE WITH UPMOST SECURITY AND CARE!
  # ---------------------------------------------------------------------------------------------
  #
  serverIp: localhost # If only accessible on your local network keep as localhost,
                      # otherwise, CHANGE TO THE SERVER'S PUBLIC IP!
  # None of this information is collected, it's used entirely for the certificate and key generation proces
  certificateDetails:
    CertAuthCommonName: LiveUpdaterCA
ftp:
  enabled: true # Required to be true if you want the plugin to set up file transfer
                # and accept plugin changes (i.e. the entire purpose of this plugin)
  port: 2121
  use-plugman: true # Kinda required so I wouldn't change it
  keystore-password: CH4NGE-TH1$-IMMEDIATELY!
  # I wouldn't change this if I were you.
  # Only change these if you really know what you're doing
  keystore-path: certs/server.jks