name: LiveUpdater
main: com.angulorecto.LiveUpdater.LiveUpdater
version: 1.0
api-version: 1.21.7
commands:
  reloadplugin:
    description: Reload a specific plugin by name
    usage: /reloadplugin <plugin-name>
permissions:
  ftpserver.admin:
    description: Allows control over the FTP server
    default: op